version: '3'
services: 
  db: 
    image: postgres:16
    environment: 
      POSTGRES_USER: kvuser
      POSTGRES_PASSWORD: kvpass
      POSTGRES_DB: kvdb
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: kvdb
      DB_USER: kvuser
      DB_PASSWORD: kvpass
volumes:
  pgdata:


